version: 0.0
os: linux

files:
  - source: /beauty/
    destination: /var/www/Beauty/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
